// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServicePilot.Infrastructure.Persistence.Models;

#nullable disable

namespace ServicePilot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609163912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServicePilot.Domain.Entities.AppSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SettingGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("setting_group")
                        .HasDefaultValueSql("'General'::character varying");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingValue")
                        .HasColumnType("text")
                        .HasColumnName("setting_value");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("app_settings_pkey");

                    b.HasIndex(new[] { "CompanyId", "SettingKey" }, "app_settings_company_id_setting_key_key")
                        .IsUnique();

                    b.ToTable("app_settings", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.AttendanceLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("CheckInLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("check_in_lat");

                    b.Property<decimal?>("CheckInLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("check_in_lng");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<decimal?>("CheckOutLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("check_out_lat");

                    b.Property<decimal?>("CheckOutLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("check_out_lng");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("IsOfflineSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_offline_sync");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("attendance_logs_pkey");

                    b.HasIndex(new[] { "CompanyId", "CheckInTime" }, "idx_attendance_company_date")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "EmployeeId", "CheckInTime" }, "idx_attendance_employee_date")
                        .IsDescending(false, true);

                    b.ToTable("attendance_logs", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("NewValues")
                        .HasColumnType("text")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("text")
                        .HasColumnName("old_values");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("table_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("branches_pkey");

                    b.HasIndex(new[] { "CompanyId" }, "idx_branches_company");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone")
                        .HasDefaultValueSql("'Asia/Dubai'::character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("companies_pkey");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("departments_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("BasicSalary")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("basic_salary");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<DateOnly?>("EmiratesIdExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("emirates_id_expiry_date");

                    b.Property<string>("EmployeeCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date")
                        .HasColumnName("joining_date");

                    b.Property<DateOnly?>("PassportExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("passport_expiry_date");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("VisaExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("visa_expiry_date");

                    b.HasKey("Id")
                        .HasName("employees_pkey");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.HasIndex(new[] { "CompanyId", "EmployeeCode" }, "employees_company_id_employee_code_key")
                        .IsUnique();

                    b.HasIndex(new[] { "BranchId" }, "idx_employees_branch");

                    b.HasIndex(new[] { "CompanyId" }, "idx_employees_company");

                    b.HasIndex(new[] { "EmiratesIdExpiryDate" }, "idx_employees_eid_expiry")
                        .HasFilter("(is_active = true)");

                    b.HasIndex(new[] { "PassportExpiryDate" }, "idx_employees_passport_expiry")
                        .HasFilter("(is_active = true)");

                    b.HasIndex(new[] { "VisaExpiryDate" }, "idx_employees_visa_expiry")
                        .HasFilter("(is_active = true)");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.EmployeeShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<TimeOnly?>("CustomEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("custom_end_time");

                    b.Property<TimeOnly?>("CustomStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("custom_start_time");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date")
                        .HasColumnName("shift_date");

                    b.Property<Guid>("ShiftTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("shift_type_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("employee_shifts_pkey");

                    b.HasIndex("ShiftTypeId");

                    b.HasIndex(new[] { "CompanyId", "ShiftDate" }, "idx_shifts_company_date")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "EmployeeId", "ShiftDate" }, "idx_shifts_employee_date")
                        .IsDescending(false, true);

                    b.ToTable("employee_shifts", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.GpsLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Accuracy")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("accuracy");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("gps_logs_pkey");

                    b.HasIndex(new[] { "CompanyId", "RecordedAt" }, "idx_gps_company_time")
                        .IsDescending(false, true);

                    b.HasIndex(new[] { "EmployeeId", "RecordedAt" }, "idx_gps_employee_time")
                        .IsDescending(false, true);

                    b.ToTable("gps_logs", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_employee_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_phone");

                    b.Property<string>("JobNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("job_number");

                    b.Property<Guid?>("JobStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_status_id");

                    b.Property<Guid?>("JobTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_type_id");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)")
                        .HasColumnName("longitude");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("ScheduledEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_end_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("jobs_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("JobStatusId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex(new[] { "AssignedEmployeeId" }, "idx_jobs_assigned_employee");

                    b.HasIndex(new[] { "CompanyId", "ScheduledAt" }, "idx_jobs_company_scheduled");

                    b.HasIndex(new[] { "CompanyId", "JobStatusId" }, "idx_jobs_company_status");

                    b.HasIndex(new[] { "CompanyId", "Priority" }, "idx_jobs_priority")
                        .HasFilter("(completed_at IS NULL)");

                    b.HasIndex(new[] { "CompanyId", "JobNumber" }, "jobs_company_id_job_number_key")
                        .IsUnique();

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("PhotoType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_type");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("job_photos_pkey");

                    b.HasIndex(new[] { "JobId" }, "idx_job_photos_job");

                    b.ToTable("job_photos", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ColorCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("color_code")
                        .HasDefaultValueSql("'#888780'::character varying");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("job_statuses_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("job_statuses", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("NewStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("new_status_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OldStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("old_status_id");

                    b.HasKey("Id")
                        .HasName("job_status_history_pkey");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("NewStatusId");

                    b.HasIndex("OldStatusId");

                    b.HasIndex(new[] { "JobId", "ChangedAt" }, "idx_job_status_history_job")
                        .IsDescending(false, true);

                    b.ToTable("job_status_history", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("EstimatedDurationMins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("estimated_duration_mins");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("job_types_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("job_types", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("leave_type_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("leave_requests_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex(new[] { "EmployeeId", "Status" }, "idx_leave_employee");

                    b.ToTable("leave_requests", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_paid");

                    b.Property<int>("MaxDaysPerYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("max_days_per_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("leave_types_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("leave_types", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("CompanyId");

                    b.HasIndex(new[] { "UserId", "IsRead" }, "idx_notifications_user_unread")
                        .HasFilter("(is_read = false)");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.OvertimeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<decimal>("HoursRequested")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("hours_requested");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date")
                        .HasColumnName("request_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("overtime_requests_pkey");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CompanyId");

                    b.HasIndex(new[] { "EmployeeId", "Status" }, "idx_overtime_employee");

                    b.ToTable("overtime_requests", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("password_reset_tokens_pkey");

                    b.HasIndex(new[] { "TokenHash" }, "idx_prt_token_hash")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId", "IsUsed" }, "idx_prt_user_used");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("positions_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Name" }, "roles_name_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.ShiftType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ColorCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("color_code")
                        .HasDefaultValueSql("'#085041'::character varying");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("shift_types_pkey");

                    b.HasIndex("CompanyId");

                    b.ToTable("shift_types", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "CompanyId" }, "idx_users_company");

                    b.HasIndex(new[] { "EmployeeId" }, "idx_users_employee");

                    b.HasIndex(new[] { "CompanyId", "Email" }, "users_company_id_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.AppSetting", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("AppSettings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("app_settings_company_id_fkey");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.AttendanceLog", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("attendance_logs_company_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Employee", "Employee")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("attendance_logs_employee_id_fkey");

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Branch", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("branches_company_id_fkey");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Department", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("departments_company_id_fkey");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Employee", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("employees_branch_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("employees_company_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("employees_department_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .HasConstraintName("employees_position_id_fkey");

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.EmployeeShift", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("EmployeeShifts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("employee_shifts_company_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeShifts")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("employee_shifts_employee_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.ShiftType", "ShiftType")
                        .WithMany("EmployeeShifts")
                        .HasForeignKey("ShiftTypeId")
                        .IsRequired()
                        .HasConstraintName("employee_shifts_shift_type_id_fkey");

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("ShiftType");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.GpsLog", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("GpsLogs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("gps_logs_company_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Employee", "Employee")
                        .WithMany("GpsLogs")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("gps_logs_employee_id_fkey");

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Job", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Employee", "AssignedEmployee")
                        .WithMany("Jobs")
                        .HasForeignKey("AssignedEmployeeId")
                        .HasConstraintName("jobs_assigned_employee_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("jobs_company_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.User", "CreatedByNavigation")
                        .WithMany("Jobs")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("jobs_created_by_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.JobStatus", "JobStatus")
                        .WithMany("Jobs")
                        .HasForeignKey("JobStatusId")
                        .HasConstraintName("jobs_job_status_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.JobType", "JobType")
                        .WithMany("Jobs")
                        .HasForeignKey("JobTypeId")
                        .HasConstraintName("jobs_job_type_id_fkey");

                    b.Navigation("AssignedEmployee");

                    b.Navigation("Company");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("JobStatus");

                    b.Navigation("JobType");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobPhoto", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Job", "Job")
                        .WithMany("JobPhotos")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_photos_job_id_fkey");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobStatus", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("JobStatuses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_statuses_company_id_fkey");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobStatusHistory", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.User", "ChangedByNavigation")
                        .WithMany("JobStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("job_status_history_changed_by_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Job", "Job")
                        .WithMany("JobStatusHistories")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_status_history_job_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.JobStatus", "NewStatus")
                        .WithMany("JobStatusHistoryNewStatuses")
                        .HasForeignKey("NewStatusId")
                        .HasConstraintName("job_status_history_new_status_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.JobStatus", "OldStatus")
                        .WithMany("JobStatusHistoryOldStatuses")
                        .HasForeignKey("OldStatusId")
                        .HasConstraintName("job_status_history_old_status_id_fkey");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("Job");

                    b.Navigation("NewStatus");

                    b.Navigation("OldStatus");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobType", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("JobTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("job_types_company_id_fkey");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.User", "ApprovedByNavigation")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("leave_requests_approved_by_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("leave_requests_company_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("leave_requests_employee_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .IsRequired()
                        .HasConstraintName("leave_requests_leave_type_id_fkey");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.LeaveType", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("LeaveTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("leave_types_company_id_fkey");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("Notifications")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("notifications_company_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("notifications_user_id_fkey");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.OvertimeRequest", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.User", "ApprovedByNavigation")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("overtime_requests_approved_by_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("overtime_requests_company_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Employee", "Employee")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("overtime_requests_employee_id_fkey");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Company");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prt_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Position", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("Positions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("positions_company_id_fkey");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.ShiftType", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("ShiftTypes")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shift_types_company_id_fkey");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.User", b =>
                {
                    b.HasOne("ServicePilot.Domain.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .HasConstraintName("users_branch_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("users_company_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Employee", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("users_employee_id_fkey");

                    b.HasOne("ServicePilot.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("users_role_id_fkey");

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Company", b =>
                {
                    b.Navigation("AppSettings");

                    b.Navigation("AttendanceLogs");

                    b.Navigation("Branches");

                    b.Navigation("Departments");

                    b.Navigation("EmployeeShifts");

                    b.Navigation("Employees");

                    b.Navigation("GpsLogs");

                    b.Navigation("JobStatuses");

                    b.Navigation("JobTypes");

                    b.Navigation("Jobs");

                    b.Navigation("LeaveRequests");

                    b.Navigation("LeaveTypes");

                    b.Navigation("Notifications");

                    b.Navigation("OvertimeRequests");

                    b.Navigation("Positions");

                    b.Navigation("ShiftTypes");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Employee", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("EmployeeShifts");

                    b.Navigation("GpsLogs");

                    b.Navigation("Jobs");

                    b.Navigation("LeaveRequests");

                    b.Navigation("OvertimeRequests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Job", b =>
                {
                    b.Navigation("JobPhotos");

                    b.Navigation("JobStatusHistories");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobStatus", b =>
                {
                    b.Navigation("JobStatusHistoryNewStatuses");

                    b.Navigation("JobStatusHistoryOldStatuses");

                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.JobType", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.LeaveType", b =>
                {
                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.ShiftType", b =>
                {
                    b.Navigation("EmployeeShifts");
                });

            modelBuilder.Entity("ServicePilot.Domain.Entities.User", b =>
                {
                    b.Navigation("JobStatusHistories");

                    b.Navigation("Jobs");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Notifications");

                    b.Navigation("OvertimeRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
