// lib/utils/exportExcel.ts
//
// Shared "professional report" Excel template — one function, reused by every
// report tab on the Reports page (and available to any future export screen).
//
// WHY THIS EXISTS:
// The old exporter (`exportCsv` in reports/page.tsx) wrote a bare comma-separated
// file with a single header row — no branding, no styling, no way to tell which
// report it was or when it was generated without opening the on-screen filters.
// Excel (.xlsx) supports real cell styling (fonts, fills, borders, frozen panes,
// number formats, column widths) that plain CSV fundamentally cannot — which is
// what makes a "professionally designed" export possible in the first place.
//
// .NET EQUIVALENT:
// Similar to building a styled report with ClosedXML/EPPlus server-side, except
// this runs entirely in the browser from data already loaded on screen — no new
// API endpoints, no extra round-trip, nothing on the backend to risk breaking.
//
// Every report gets the same look:
//   ┌─────────────────────────────────────────────┐
//   │ ServicePilot                                 │  ← brand bar (dark navy)
//   │ Attendance Report                            │  ← report title
//   │ 1 May 2026 – 31 May 2026                     │  ← subtitle / filter summary
//   │ Generated 9 Jun 2026, 14:32 by admin@…(Admin)│  ← provenance line
//   │                                               │
//   │ EMPLOYEE | BRANCH | PRESENT | LATE | …       │  ← styled header row (blue)
//   │ Jane Doe | Dubai  |   22    |  1   | …       │  ← zebra-striped data rows
//   │ ...                                          │
//   └─────────────────────────────────────────────┘

import ExcelJS from 'exceljs';

export interface ExportColumn {
  /** Column header text shown in the styled header row. */
  header: string;
  /** Key used to read the value out of each row object. */
  key: string;
  /** Optional explicit column width (Excel "characters" unit). Auto-sized if omitted. */
  width?: number;
  /** Optional Excel number format, e.g. '#,##0.0' or '0.0"h"' for hours. */
  numFmt?: string;
  /** Optional cell alignment — defaults to 'left'. */
  align?: 'left' | 'right' | 'center';
}

export interface ExportReportOptions {
  /** Report title, e.g. "Attendance Report". Also used as the worksheet name. */
  title: string;
  /** Optional subtitle line — typically the active date range / filter summary. */
  subtitle?: string;
  /** Optional "generated by" identity line, e.g. "admin@acme.com (Admin)". */
  generatedBy?: string;
  columns: ExportColumn[];
  rows: Record<string, any>[];
  /** Download filename WITHOUT extension — ".xlsx" is appended automatically. */
  filename: string;
}

const BRAND_NAVY = 'FF1E3A5F';
const HEADER_BLUE = 'FF2563EB';
const ZEBRA_FILL = 'FFF8FAFC';
const BORDER_GREY = 'FFE2E8F0';
const TEXT_SLATE = 'FF334155';
const MUTED_SLATE = 'FF94A3B8';

/**
 * Builds a branded, styled .xlsx workbook for a single report and triggers a
 * browser download. All styling lives here so every report tab looks identical
 * and consistent — change the palette once, every export updates.
 */
export async function exportReportToExcel(opts: ExportReportOptions) {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'ServicePilot';
  wb.created = new Date();

  // Worksheet names can't exceed 31 chars or contain []:*?/\
  const sheetName = opts.title.replace(/[\[\]:*?/\\]/g, '').slice(0, 31) || 'Report';
  const ws = wb.addWorksheet(sheetName, {
    pageSetup: { paperSize: 9, orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0 },
    views: [{ showGridLines: false }],
  });

  const colCount = Math.max(opts.columns.length, 1);
  let r = 1;

  // ── Brand bar ──────────────────────────────────────────────
  mergeAndStyle(ws, r, colCount, {
    value: 'ServicePilot',
    font: { name: 'Calibri', size: 16, bold: true, color: { argb: 'FFFFFFFF' } },
    fill: BRAND_NAVY,
    height: 30,
  });
  r++;

  // ── Report title ───────────────────────────────────────────
  mergeAndStyle(ws, r, colCount, {
    value: opts.title,
    font: { name: 'Calibri', size: 14, bold: true, color: { argb: TEXT_SLATE } },
    height: 24,
  });
  r++;

  // ── Subtitle (date range / filter summary) ────────────────
  if (opts.subtitle) {
    mergeAndStyle(ws, r, colCount, {
      value: opts.subtitle,
      font: { name: 'Calibri', size: 11, color: { argb: TEXT_SLATE } },
      height: 19,
    });
    r++;
  }

  // ── Provenance line ────────────────────────────────────────
  const generatedAt = new Date().toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  mergeAndStyle(ws, r, colCount, {
    value: `Generated ${generatedAt}${opts.generatedBy ? ` · ${opts.generatedBy}` : ''} · ServicePilot Reports`,
    font: { name: 'Calibri', size: 9, italic: true, color: { argb: MUTED_SLATE } },
    height: 16,
  });
  r++;

  r++; // blank spacer row before the table

  // ── Column header row ──────────────────────────────────────
  const headerRowIdx = r;
  const headerRow = ws.getRow(headerRowIdx);
  opts.columns.forEach((col, i) => {
    const cell = headerRow.getCell(i + 1);
    cell.value = col.header;
    cell.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: HEADER_BLUE } };
    cell.alignment = { vertical: 'middle', horizontal: col.align ?? 'left' };
    cell.border = { bottom: { style: 'medium', color: { argb: HEADER_BLUE } } };
  });
  headerRow.height = 22;
  r++;

  // ── Data rows (zebra striping + thin borders) ─────────────
  opts.rows.forEach((row, idx) => {
    const excelRow = ws.getRow(r + idx);
    opts.columns.forEach((col, cIdx) => {
      const cell = excelRow.getCell(cIdx + 1);
      const value = row[col.key];
      cell.value = value === undefined || value === null ? '' : value;
      if (col.numFmt && typeof value === 'number') cell.numFmt = col.numFmt;
      cell.font = { name: 'Calibri', size: 10, color: { argb: TEXT_SLATE } };
      cell.alignment = { vertical: 'middle', horizontal: col.align ?? 'left', wrapText: false };
      cell.border = { bottom: { style: 'hair', color: { argb: BORDER_GREY } } };
      if (idx % 2 === 1) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: ZEBRA_FILL } };
      }
    });
    excelRow.height = 18;
  });

  // ── Column widths — fit to header/content, capped so nothing runs away ──
  opts.columns.forEach((col, i) => {
    if (col.width) {
      ws.getColumn(i + 1).width = col.width;
      return;
    }
    const longest = opts.rows.reduce(
      (max, row) => Math.max(max, String(row[col.key] ?? '').length),
      col.header.length
    );
    ws.getColumn(i + 1).width = Math.min(Math.max(longest + 3, 12), 42);
  });

  // Freeze everything above (and including) the header row so it stays visible
  // while scrolling through long reports.
  ws.views = [{ state: 'frozen', ySplit: headerRowIdx, showGridLines: false }];

  // ── Generate the file and trigger a browser download ──────
  const buffer = await wb.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${opts.filename}.xlsx`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

// ── Internal helper — merge a full-width row and apply a consistent style ──
function mergeAndStyle(
  ws: ExcelJS.Worksheet,
  rowIdx: number,
  colCount: number,
  opts: { value: string; font: Partial<ExcelJS.Font>; fill?: string; height: number }
) {
  ws.mergeCells(rowIdx, 1, rowIdx, colCount);
  const cell = ws.getCell(rowIdx, 1);
  cell.value = opts.value;
  cell.font = opts.font;
  cell.alignment = { vertical: 'middle', horizontal: 'left' };
  if (opts.fill) {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: opts.fill } };
    // Paint the fill across every merged cell, not just the anchor — Excel
    // only renders the top-left cell's fill on a merge by default otherwise
    // when grid lines are hidden it can look like the bar stops short.
    for (let c = 2; c <= colCount; c++) {
      const sibling = ws.getCell(rowIdx, c);
      sibling.fill = cell.fill;
    }
  }
  ws.getRow(rowIdx).height = opts.height;
}
