'use client';
// app/(dashboard)/reports/page.tsx
// Reports hub — 4 report tabs: Attendance, Jobs, Leave, Expiry

import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import apiClient from '@/lib/api/client';
import { useAuthStore } from '@/lib/store/auth';
import { useTableSort, thCls, SortArrow } from '@/lib/hooks/useTableSort';
import { exportReportToExcel, type ExportColumn } from '@/lib/utils/exportExcel';

// ── Report API calls ──────────────────────────────────────────
function useAttendanceReport(params: Record<string, any>, enabled: boolean) {
  return useQuery({
    queryKey: ['report-attendance', params],
    queryFn: async () => { const r = await apiClient.get('/reports/attendance', { params }); return r.data.data; },
    enabled: enabled && !!params.from && !!params.to,
    staleTime: 5 * 60 * 1000,
  });
}

function useJobReport(params: Record<string, any>, enabled: boolean) {
  return useQuery({
    queryKey: ['report-jobs', params],
    queryFn: async () => { const r = await apiClient.get('/reports/jobs', { params }); return r.data.data; },
    enabled: enabled && !!params.from && !!params.to,
    staleTime: 5 * 60 * 1000,
  });
}

function useLeaveReport(params: Record<string, any>, enabled: boolean) {
  return useQuery({
    queryKey: ['report-leave', params],
    queryFn: async () => { const r = await apiClient.get('/reports/leave', { params }); return r.data.data; },
    enabled,
    staleTime: 5 * 60 * 1000,
  });
}

function useExpiryReport(days: number, enabled: boolean) {
  return useQuery({
    queryKey: ['report-expiry', days],
    queryFn: async () => { const r = await apiClient.get('/reports/expiry', { params: { days } }); return r.data.data; },
    enabled,
    staleTime: 5 * 60 * 1000,
  });
}

const TABS = [
  { id: 'attendance', label: 'Attendance',   icon: '🕐' },
  { id: 'jobs',       label: 'Jobs',         icon: '💼' },
  { id: 'leave',      label: 'Leave',        icon: '📋' },
  { id: 'expiry',     label: 'Doc Expiry',   icon: '🪪' },
] as const;

type Tab = typeof TABS[number]['id'];

// Default date range:
//   Job / Attendance default: 1 Jan of current year → today (shows all year's data on open)
const today = new Date().toISOString().slice(0, 10);
const firstOfYear  = new Date(new Date().getFullYear(), 0, 1).toISOString().slice(0, 10);
const firstOfMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10);

// Friendly "1 Jan 2026 – 9 Jun 2026" range string used in export subtitles.
function fmtRange(from: string, to: string) {
  const f = (d: string) => new Date(d).toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' });
  return `${f(from)} – ${f(to)}`;
}

export default function ReportsPage() {
  const [tab, setTab] = useState<Tab>('attendance');
  // Attendance: current-month default (daily data — keeps rows manageable)
  // Jobs: full-year default so existing jobs are visible immediately
  const [atParams, setAtParams] = useState({ from: firstOfMonth, to: today });
  const [jobParams, setJobParams] = useState({ from: firstOfYear,  to: today });
  const [leaveYear, setLeaveYear] = useState(new Date().getFullYear());
  const [expiryDays, setExpiryDays] = useState(30);

  const attReport  = useAttendanceReport(atParams,  tab === 'attendance');
  const jobReport  = useJobReport(jobParams,         tab === 'jobs');
  const leaveReport= useLeaveReport({ year: leaveYear }, tab === 'leave');
  const expiryReport = useExpiryReport(expiryDays,  tab === 'expiry');

  // "Generated by" identity line for exports — AuthUser has no fullName, so
  // email + role is the most identifying combination available.
  const { user } = useAuthStore();
  const generatedBy = user ? `${user.email} (${user.role})` : undefined;

  // Client-side search + sort for each report's table — purely additive, the
  // underlying query data and pagination are untouched.
  const attSort    = useTableSort(attReport.data?.rows ?? [],   'employeeName');
  const jobSort    = useTableSort(jobReport.data?.jobs ?? [],   'jobNumber');
  const leaveSort  = useTableSort(leaveReport.data?.rows ?? [], 'employeeName');
  const expirySort = useTableSort(expiryReport.data?.rows ?? [],'employeeName');

  async function handleExport() {
    if (tab === 'attendance' && attReport.data?.rows?.length) {
      const rows = attReport.data.rows;
      const cols: ExportColumn[] = [
        { header: 'Employee',     key: 'employeeName' },
        { header: 'Code',         key: 'employeeCode' },
        { header: 'Branch',       key: 'branchName' },
        { header: 'Present Days', key: 'presentDays',  align: 'right', numFmt: '0' },
        { header: 'Late Days',    key: 'lateDays',     align: 'right', numFmt: '0' },
        { header: 'Absent Days',  key: 'absentDays',   align: 'right', numFmt: '0' },
        { header: 'Total Hours',  key: 'totalHours',   align: 'right', numFmt: '0.0"h"' },
        { header: 'Avg Check-in', key: 'avgCheckIn' },
      ];
      await exportReportToExcel({
        title: 'Attendance Report',
        subtitle: `${fmtRange(atParams.from, atParams.to)} · ${rows.length} employee${rows.length !== 1 ? 's' : ''}`,
        generatedBy,
        filename: `attendance-${atParams.from}-to-${atParams.to}`,
        columns: cols,
        rows: rows.map((r: any) => ({
          employeeName: r.employeeName,
          employeeCode: r.employeeCode,
          branchName: r.branchName ?? '—',
          presentDays: r.presentDays,
          lateDays: r.lateDays,
          absentDays: r.absentDays,
          totalHours: Number((r.totalHoursWorked ?? 0).toFixed(1)),
          avgCheckIn: r.averageCheckIn ?? '—',
        })),
      });
    } else if (tab === 'jobs' && jobReport.data?.jobs?.length) {
      const jobs = jobReport.data.jobs;
      const cols: ExportColumn[] = [
        { header: 'Job #',       key: 'jobNumber',   width: 16 },
        { header: 'Customer',    key: 'customerName' },
        { header: 'Type',        key: 'jobTypeName' },
        { header: 'Status',      key: 'statusName' },
        { header: 'Assigned To', key: 'assignedTo' },
        { header: 'Priority',    key: 'priorityLabel' },
        { header: 'Scheduled',   key: 'scheduledAt', numFmt: 'dd mmm yyyy' },
        { header: 'Completed',   key: 'completedAt', numFmt: 'dd mmm yyyy' },
      ];
      await exportReportToExcel({
        title: 'Jobs Report',
        subtitle: `${fmtRange(jobParams.from, jobParams.to)} · ${jobs.length} job${jobs.length !== 1 ? 's' : ''} · ${jobReport.data.completionRate ?? 0}% completion rate`,
        generatedBy,
        filename: `jobs-${jobParams.from}-to-${jobParams.to}`,
        columns: cols,
        rows: jobs.map((r: any) => ({
          jobNumber: r.jobNumber,
          customerName: r.customerName,
          jobTypeName: r.jobTypeName ?? '—',
          statusName: r.statusName ?? '—',
          assignedTo: r.assignedEmployeeName ? `${r.assignedEmployeeName} (${r.assignedEmployeeCode ?? ''})` : 'Unassigned',
          priorityLabel: r.priorityLabel,
          scheduledAt: r.scheduledAt ? new Date(r.scheduledAt) : null,
          completedAt: r.completedAt ? new Date(r.completedAt) : null,
        })),
      });
    } else if (tab === 'leave' && leaveReport.data?.rows?.length) {
      const rows = leaveReport.data.rows;
      const cols: ExportColumn[] = [
        { header: 'Employee',              key: 'employeeName' },
        { header: 'Code',                  key: 'employeeCode' },
        { header: 'Department',            key: 'departmentName' },
        { header: 'Approved Leave (days)', key: 'approvedLeaveDays', align: 'right', numFmt: '0' },
        { header: 'Pending Leave (days)',  key: 'pendingLeaveDays',  align: 'right', numFmt: '0' },
        { header: 'Approved OT (hrs)',     key: 'approvedOvertimeHours', align: 'right', numFmt: '0.0' },
        { header: 'Pending OT (hrs)',      key: 'pendingOvertimeHours',  align: 'right', numFmt: '0.0' },
        { header: 'Rejections',            key: 'rejections', align: 'right', numFmt: '0' },
      ];
      await exportReportToExcel({
        title: 'Leave & Overtime Report',
        subtitle: `Year ${leaveYear} · ${rows.length} employee${rows.length !== 1 ? 's' : ''}`,
        generatedBy,
        filename: `leave-overtime-${leaveYear}`,
        columns: cols,
        rows: rows.map((r: any) => ({
          employeeName: r.employeeName,
          employeeCode: r.employeeCode,
          departmentName: r.departmentName ?? '—',
          approvedLeaveDays: r.approvedLeaveDays,
          pendingLeaveDays: r.pendingLeaveDays,
          approvedOvertimeHours: Number(r.approvedOvertimeHours ?? 0),
          pendingOvertimeHours: Number(r.pendingOvertimeHours ?? 0),
          rejections: (r.rejectedLeaveCount ?? 0) + (r.rejectedOvertimeCount ?? 0),
        })),
      });
    } else if (tab === 'expiry' && expiryReport.data?.rows?.length) {
      // Flatten one row-per-employee into one row-per-document so every
      // expiring item is its own sortable/filterable line in the spreadsheet.
      const flat: Record<string, any>[] = [];
      const addDoc = (e: any, doc: string, expiry: string | null, daysLeft: number | null) => {
        if (!expiry || daysLeft === null) return;
        flat.push({
          employeeName: e.employeeName,
          employeeCode: e.employeeCode,
          branchName: e.branchName ?? '—',
          phoneNumber: e.phoneNumber ?? '—',
          document: doc,
          expiryDate: expiry,
          daysLeft,
          status: daysLeft < 0 ? 'Expired' : daysLeft <= 30 ? 'Expiring soon' : 'OK',
        });
      };
      expiryReport.data.rows.forEach((e: any) => {
        addDoc(e, 'Visa',        e.visaExpiryDate,       e.visaDaysLeft);
        addDoc(e, 'Passport',    e.passportExpiryDate,   e.passportDaysLeft);
        addDoc(e, 'Emirates ID', e.emiratesIdExpiryDate, e.emiratesIdDaysLeft);
      });
      const cols: ExportColumn[] = [
        { header: 'Employee',    key: 'employeeName' },
        { header: 'Code',        key: 'employeeCode' },
        { header: 'Branch',      key: 'branchName' },
        { header: 'Phone',       key: 'phoneNumber' },
        { header: 'Document',    key: 'document' },
        { header: 'Expiry Date', key: 'expiryDate' },
        { header: 'Days Left',   key: 'daysLeft', align: 'right', numFmt: '0' },
        { header: 'Status',      key: 'status' },
      ];
      await exportReportToExcel({
        title: 'Document Expiry Report',
        subtitle: `Documents expiring within ${expiryDays} days · ${expiryReport.data.totalAffected ?? 0} employee${(expiryReport.data.totalAffected ?? 0) !== 1 ? 's' : ''} affected`,
        generatedBy,
        filename: `document-expiry-within-${expiryDays}-days`,
        columns: cols,
        rows: flat,
      });
    }
  }

  return (
    <div>
      {/* Header */}
      <div className="mb-6 flex items-start justify-between">
        <div>
          <h1 className="text-[22px] font-bold tracking-tight text-gray-900">Analytics &amp; Reports</h1>
          <p className="mt-0.5 text-[13px] text-gray-500">Performance insights and workforce analytics</p>
        </div>
        <button onClick={handleExport} title="Download a professionally formatted Excel (.xlsx) report"
          className="flex h-9 items-center gap-1.5 rounded-lg bg-btn px-4 text-[13px] font-semibold text-white hover:bg-btn-hover transition-colors">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
          Export to Excel
        </button>
      </div>

      {/* Tab bar — matches your Figma: Overview | Attendance | Productivity | Jobs */}
      <div className="mb-6 flex gap-1 rounded-xl border border-gray-200 bg-white p-1.5 shadow-sm w-fit">
        {TABS.map(t => (
          <button key={t.id} onClick={() => setTab(t.id)}
            className={`flex items-center gap-2 rounded-lg px-5 py-2 text-[13px] font-medium transition-colors ${tab === t.id ? 'bg-btn text-white shadow-sm' : 'text-gray-600 hover:bg-gray-50'}`}>
            {t.label}
          </button>
        ))}
      </div>

      {/* ── ATTENDANCE REPORT ── */}
      {tab === 'attendance' && (
        <div>
          {/* Summary metric cards — like your Figma */}
          {attReport.data && (
            <div className="mb-5 grid grid-cols-4 gap-3.5">
              {[
                { label: 'Avg Attendance', value: `${(attReport.data.rows?.length ?? 0) > 0 ? Math.round((attReport.data.rows ?? []).reduce((a: number, r: any) => a + ((r.presentDays ?? 0) / (attReport.data.totalDays || 1) * 100), 0) / attReport.data.rows.length) : 0}%`, trend: '↑', cls: 'text-green-600' },
                { label: 'Total Days',     value: attReport.data.totalDays ?? 0, trend: null,  cls: 'text-gray-900' },
                { label: 'Employees',      value: attReport.data.rows?.length ?? 0, trend: null,  cls: 'text-gray-900' },
                { label: 'Avg Hours/Day',  value: `${(attReport.data.rows?.length ?? 0) > 0 ? ((attReport.data.rows ?? []).reduce((a: number, r: any) => a + (r.averageHoursPerDay ?? 0), 0) / attReport.data.rows.length).toFixed(1) : 0}h`, trend: null, cls: 'text-gray-900' },
              ].map(card => (
                <div key={card.label} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                  <div className="mb-1 text-[12px] text-gray-500">{card.label}</div>
                  <div className={`text-[28px] font-bold tabular-nums tracking-tight ${card.cls}`}>
                    {card.trend && <span className="mr-1 text-[16px]">{card.trend}</span>}
                    {card.value}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Date filters */}
          <div className="mb-4 flex items-center gap-3">
            <input type="date" value={atParams.from} onChange={e => setAtParams(p => ({ ...p, from: e.target.value }))}
              className="h-9 rounded-lg border border-gray-200 bg-white px-3 text-[13px] text-gray-700 outline-none focus:border-blue-600"/>
            <span className="text-[13px] text-gray-400">to</span>
            <input type="date" value={atParams.to} onChange={e => setAtParams(p => ({ ...p, to: e.target.value }))}
              className="h-9 rounded-lg border border-gray-200 bg-white px-3 text-[13px] text-gray-700 outline-none focus:border-blue-600"/>
            {attReport.isFetching && <Spinner />}
          </div>

          {/* Search + result count */}
          {attReport.data && (
            <div className="mb-4 flex items-center gap-3">
              <div className="flex h-9 flex-1 max-w-sm items-center gap-2 rounded-lg border border-gray-200 bg-white px-3.5">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
                <input value={attSort.search} onChange={e => attSort.setSearch(e.target.value)} placeholder="Search by employee, code or branch..."
                  className="flex-1 bg-transparent text-[13px] text-gray-900 outline-none placeholder:text-gray-400"/>
                {attSort.search && (
                  <button onClick={() => attSort.setSearch('')} className="text-gray-400 hover:text-gray-600">
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
                  </button>
                )}
              </div>
              <span className="text-[12px] text-gray-400">{attSort.sorted.length} of {attReport.data.rows?.length ?? 0} employee{(attReport.data.rows?.length ?? 0) !== 1 ? 's' : ''}</span>
            </div>
          )}

          <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
            {attReport.isLoading && <TableSkeleton cols={7} rows={6} />}
            {attReport.data && (
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gray-100 bg-gray-50/50">
                    {[
                      { key: 'employeeName', label: 'Employee' },
                      { key: 'branchName',   label: 'Branch' },
                      { key: 'presentDays',  label: 'Present' },
                      { key: 'lateDays',     label: 'Late' },
                      { key: 'absentDays',   label: 'Absent' },
                      { key: 'totalHoursWorked', label: 'Total Hours' },
                      { key: 'averageCheckIn',   label: 'Avg Check-in' },
                    ].map(h => (
                      <th key={h.key} onClick={() => attSort.toggleSort(h.key)} className={thCls(attSort.sortKey, h.key, attSort.sortDir)}>
                        {h.label} <SortArrow col={h.key} sortKey={attSort.sortKey} sortDir={attSort.sortDir}/>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                  {attSort.sorted.map((row: any) => (
                    <tr key={row.employeeId} className="hover:bg-gray-50/50 transition-colors">
                      <td className="px-5 py-3.5">
                        <div className="text-[13px] font-medium text-gray-900">{row.employeeName}</div>
                        <div className="text-[11px] font-mono text-gray-400">{row.employeeCode}</div>
                      </td>
                      <td className="px-5 py-3.5 text-[13px] text-gray-700">{row.branchName || '—'}</td>
                      <td className="px-5 py-3.5"><span className="font-medium text-green-700">{row.presentDays}</span></td>
                      <td className="px-5 py-3.5"><span className="font-medium text-amber-600">{row.lateDays}</span></td>
                      <td className="px-5 py-3.5"><span className="font-medium text-red-600">{row.absentDays}</span></td>
                      <td className="px-5 py-3.5 text-[13px] text-gray-700 tabular-nums">{row.totalHoursWorked?.toFixed(1)}h</td>
                      <td className="px-5 py-3.5 text-[13px] text-gray-700">{row.averageCheckIn || '—'}</td>
                    </tr>
                  ))}
                  {attSort.sorted.length === 0 && (
                    <tr><td colSpan={7} className="py-12 text-center text-[13px] text-gray-400">No employees match your search</td></tr>
                  )}
                </tbody>
              </table>
            )}
            {!attReport.isLoading && !attReport.data && (
              <div className="py-12 text-center text-[13px] text-gray-400">Select a date range to generate the report</div>
            )}
          </div>
        </div>
      )}

      {/* ── JOB REPORT ── */}
      {tab === 'jobs' && (
        <div>
          {jobReport.data && (
            <div className="mb-5 grid grid-cols-4 gap-3.5">
              {[
                { label: 'Total Jobs',      value: jobReport.data.totalJobs,     cls: 'text-gray-900' },
                { label: 'Completed',       value: jobReport.data.completedJobs, cls: 'text-green-600' },
                { label: 'Active',          value: jobReport.data.activeJobs,    cls: 'text-blue-600'  },
                { label: 'Completion Rate', value: `${jobReport.data.completionRate}%`, cls: 'text-green-600' },
              ].map(card => (
                <div key={card.label} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm">
                  <div className="mb-1 text-[12px] text-gray-500">{card.label}</div>
                  <div className={`text-[28px] font-bold tabular-nums tracking-tight ${card.cls}`}>{card.value}</div>
                </div>
              ))}
            </div>
          )}

          <div className="mb-4 flex items-center gap-3">
            <input type="date" value={jobParams.from} onChange={e => setJobParams(p => ({ ...p, from: e.target.value }))}
              className="h-9 rounded-lg border border-gray-200 bg-white px-3 text-[13px] text-gray-700 outline-none focus:border-blue-600"/>
            <span className="text-[13px] text-gray-400">to</span>
            <input type="date" value={jobParams.to} onChange={e => setJobParams(p => ({ ...p, to: e.target.value }))}
              className="h-9 rounded-lg border border-gray-200 bg-white px-3 text-[13px] text-gray-700 outline-none focus:border-blue-600"/>
            {jobReport.isFetching && <Spinner />}
          </div>

          {/* Search + result count */}
          {jobReport.data && (
            <div className="mb-4 flex items-center gap-3">
              <div className="flex h-9 flex-1 max-w-sm items-center gap-2 rounded-lg border border-gray-200 bg-white px-3.5">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
                <input value={jobSort.search} onChange={e => jobSort.setSearch(e.target.value)} placeholder="Search by job #, customer, type or status..."
                  className="flex-1 bg-transparent text-[13px] text-gray-900 outline-none placeholder:text-gray-400"/>
                {jobSort.search && (
                  <button onClick={() => jobSort.setSearch('')} className="text-gray-400 hover:text-gray-600">
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
                  </button>
                )}
              </div>
              <span className="text-[12px] text-gray-400">{jobSort.sorted.length} of {jobReport.data.jobs?.length ?? 0} job{(jobReport.data.jobs?.length ?? 0) !== 1 ? 's' : ''}</span>
            </div>
          )}

          <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
            {jobReport.isLoading && <TableSkeleton cols={7} rows={5} />}
            {jobReport.data && (
              <>
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-gray-100 bg-gray-50/50">
                      {[
                        { key: 'jobNumber',   label: 'Job #' },
                        { key: 'customerName',label: 'Customer' },
                        { key: 'jobTypeName', label: 'Type' },
                        { key: 'statusName',  label: 'Status' },
                        { key: 'assignedEmployeeName', label: 'Assigned To' },
                        { key: 'scheduledAt', label: 'Scheduled' },
                        { key: 'priorityLabel', label: 'Priority' },
                      ].map(h => (
                        <th key={h.key} onClick={() => jobSort.toggleSort(h.key)} className={thCls(jobSort.sortKey, h.key, jobSort.sortDir)}>
                          {h.label} <SortArrow col={h.key} sortKey={jobSort.sortKey} sortDir={jobSort.sortDir}/>
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-50">
                    {jobSort.sorted.map((row: any) => (
                      <tr key={row.id} className="hover:bg-gray-50/50 transition-colors">
                        <td className="px-5 py-3.5">
                          <span className="font-mono text-[13px] font-semibold text-blue-700">{row.jobNumber}</span>
                        </td>
                        <td className="px-5 py-3.5">
                          <div className="text-[13px] font-medium text-gray-900">{row.customerName}</div>
                        </td>
                        <td className="px-5 py-3.5 text-[13px] text-gray-500">{row.jobTypeName || '—'}</td>
                        <td className="px-5 py-3.5">
                          <span className="rounded-full px-2.5 py-0.5 text-[11px] font-medium"
                            style={{
                              backgroundColor: row.statusColor ? `${row.statusColor}22` : '#f1f5f9',
                              color: row.statusColor ?? '#475569',
                            }}>
                            {row.statusName || '—'}
                          </span>
                        </td>
                        <td className="px-5 py-3.5 text-[13px] text-gray-700">
                          {row.assignedEmployeeName
                            ? <><div>{row.assignedEmployeeName}</div><div className="text-[11px] font-mono text-gray-400">{row.assignedEmployeeCode}</div></>
                            : <span className="text-gray-400 italic">Unassigned</span>}
                        </td>
                        <td className="px-5 py-3.5 text-[13px] text-gray-500">
                          {row.scheduledAt ? new Date(row.scheduledAt).toLocaleDateString('en-GB', { day:'2-digit', month:'short', year:'numeric' }) : '—'}
                        </td>
                        <td className="px-5 py-3.5">
                          <span className={`text-[12px] font-medium ${
                            row.priorityLabel === 'Critical' ? 'text-red-600' :
                            row.priorityLabel === 'High' ? 'text-orange-600' :
                            row.priorityLabel === 'Medium' ? 'text-amber-600' : 'text-gray-500'
                          }`}>{row.priorityLabel}</span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                {(!jobReport.data.jobs || jobReport.data.jobs.length === 0) && (
                  <div className="py-12 text-center text-[13px] text-gray-400">
                    No jobs found in this date range — try widening the range
                  </div>
                )}
                {jobReport.data.jobs?.length > 0 && jobSort.sorted.length === 0 && (
                  <div className="py-12 text-center text-[13px] text-gray-400">No jobs match your search</div>
                )}
              </>
            )}
            {!jobReport.isLoading && !jobReport.data && (
              <div className="py-12 text-center text-[13px] text-gray-400">Select a date range to generate the report</div>
            )}
          </div>
        </div>
      )}

      {/* ── LEAVE REPORT ── */}
      {tab === 'leave' && (
        <div>
          <div className="mb-4 flex items-center gap-3">
            <select value={leaveYear} onChange={e => setLeaveYear(Number(e.target.value))}
              className="h-9 rounded-lg border border-gray-200 bg-white px-3 text-[13px] text-gray-700 outline-none focus:border-blue-600">
              {[2024, 2025, 2026, 2027].map(y => <option key={y} value={y}>{y}</option>)}
            </select>
            {leaveReport.isFetching && <Spinner />}
          </div>

          {/* Search + result count */}
          {leaveReport.data && (
            <div className="mb-4 flex items-center gap-3">
              <div className="flex h-9 flex-1 max-w-sm items-center gap-2 rounded-lg border border-gray-200 bg-white px-3.5">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
                <input value={leaveSort.search} onChange={e => leaveSort.setSearch(e.target.value)} placeholder="Search by employee, code or department..."
                  className="flex-1 bg-transparent text-[13px] text-gray-900 outline-none placeholder:text-gray-400"/>
                {leaveSort.search && (
                  <button onClick={() => leaveSort.setSearch('')} className="text-gray-400 hover:text-gray-600">
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
                  </button>
                )}
              </div>
              <span className="text-[12px] text-gray-400">{leaveSort.sorted.length} of {leaveReport.data.rows?.length ?? 0} employee{(leaveReport.data.rows?.length ?? 0) !== 1 ? 's' : ''}</span>
            </div>
          )}

          <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
            {leaveReport.isLoading && <TableSkeleton cols={7} rows={5} />}
            {leaveReport.data && (
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gray-100 bg-gray-50/50">
                    {[
                      { key: 'employeeName',   label: 'Employee' },
                      { key: 'departmentName', label: 'Department' },
                      { key: 'approvedLeaveDays', label: 'Leave Days' },
                      { key: 'pendingLeaveDays',  label: 'Pending Leave' },
                      { key: 'approvedOvertimeHours', label: 'OT Hours' },
                      { key: 'pendingOvertimeHours',  label: 'Pending OT' },
                      { key: 'rejectedLeaveCount',    label: 'Rejections' },
                    ].map(h => (
                      <th key={h.key} onClick={() => leaveSort.toggleSort(h.key)} className={thCls(leaveSort.sortKey, h.key, leaveSort.sortDir)}>
                        {h.label} <SortArrow col={h.key} sortKey={leaveSort.sortKey} sortDir={leaveSort.sortDir}/>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                  {leaveSort.sorted.map((row: any) => (
                    <tr key={row.employeeId} className="hover:bg-gray-50/50 transition-colors">
                      <td className="px-5 py-3.5">
                        <div className="text-[13px] font-medium text-gray-900">{row.employeeName}</div>
                        <div className="text-[11px] font-mono text-gray-400">{row.employeeCode}</div>
                      </td>
                      <td className="px-5 py-3.5 text-[13px] text-gray-700">{row.departmentName || '—'}</td>
                      <td className="px-5 py-3.5 font-medium text-green-700 tabular-nums">{row.approvedLeaveDays}</td>
                      <td className="px-5 py-3.5 text-amber-600 tabular-nums">{row.pendingLeaveDays}</td>
                      <td className="px-5 py-3.5 font-medium text-blue-700 tabular-nums">{row.approvedOvertimeHours}h</td>
                      <td className="px-5 py-3.5 text-amber-600 tabular-nums">{row.pendingOvertimeHours}h</td>
                      <td className="px-5 py-3.5 text-[13px] text-gray-500 tabular-nums">{row.rejectedLeaveCount + row.rejectedOvertimeCount}</td>
                    </tr>
                  ))}
                  {leaveSort.sorted.length === 0 && (
                    <tr><td colSpan={7} className="py-12 text-center text-[13px] text-gray-400">No employees match your search</td></tr>
                  )}
                </tbody>
              </table>
            )}
          </div>
        </div>
      )}

      {/* ── EXPIRY REPORT ── */}
      {tab === 'expiry' && (
        <div>
          <div className="mb-4 flex items-center gap-3">
            <select value={expiryDays} onChange={e => setExpiryDays(Number(e.target.value))}
              className="h-9 rounded-lg border border-gray-200 bg-white px-3 text-[13px] text-gray-700 outline-none focus:border-blue-600">
              <option value={30}>Expiring in 30 days</option>
              <option value={60}>Expiring in 60 days</option>
              <option value={90}>Expiring in 90 days</option>
              <option value={365}>Expiring in 1 year</option>
            </select>
            {expiryReport.isFetching && <Spinner />}
            {expiryReport.data && (
              <span className="text-[13px] font-medium text-red-600">
                {expiryReport.data.totalAffected} employee{expiryReport.data.totalAffected !== 1 ? 's' : ''} affected
              </span>
            )}
          </div>

          {/* Search + result count */}
          {expiryReport.data && expiryReport.data.rows?.length > 0 && (
            <div className="mb-4 flex items-center gap-3">
              <div className="flex h-9 flex-1 max-w-sm items-center gap-2 rounded-lg border border-gray-200 bg-white px-3.5">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#94a3b8" strokeWidth="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
                <input value={expirySort.search} onChange={e => expirySort.setSearch(e.target.value)} placeholder="Search by employee, code, branch or phone..."
                  className="flex-1 bg-transparent text-[13px] text-gray-900 outline-none placeholder:text-gray-400"/>
                {expirySort.search && (
                  <button onClick={() => expirySort.setSearch('')} className="text-gray-400 hover:text-gray-600">
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>
                  </button>
                )}
              </div>
              <span className="text-[12px] text-gray-400">{expirySort.sorted.length} of {expiryReport.data.rows?.length ?? 0} employee{(expiryReport.data.rows?.length ?? 0) !== 1 ? 's' : ''}</span>
            </div>
          )}

          <div className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
            {expiryReport.isLoading && <TableSkeleton cols={6} rows={4} />}
            {expiryReport.data && (
              <table className="w-full">
                <thead>
                  <tr className="border-b border-gray-100 bg-gray-50/50">
                    {[
                      { key: 'employeeName',      label: 'Employee' },
                      { key: 'branchName',        label: 'Branch' },
                      { key: 'phoneNumber',       label: 'Phone' },
                      { key: 'visaDaysLeft',      label: 'Visa' },
                      { key: 'passportDaysLeft',  label: 'Passport' },
                      { key: 'emiratesIdDaysLeft',label: 'Emirates ID' },
                    ].map(h => (
                      <th key={h.key} onClick={() => expirySort.toggleSort(h.key)} className={thCls(expirySort.sortKey, h.key, expirySort.sortDir)}>
                        {h.label} <SortArrow col={h.key} sortKey={expirySort.sortKey} sortDir={expirySort.sortDir}/>
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                  {expirySort.sorted.map((row: any) => (
                    <tr key={row.employeeId} className={`transition-colors hover:bg-gray-50/50 ${row.hasExpired ? 'bg-red-50/30' : ''}`}>
                      <td className="px-5 py-3.5">
                        <div className="text-[13px] font-medium text-gray-900">{row.employeeName}</div>
                        <div className="text-[11px] font-mono text-gray-400">{row.employeeCode}</div>
                      </td>
                      <td className="px-5 py-3.5 text-[13px] text-gray-700">{row.branchName || '—'}</td>
                      <td className="px-5 py-3.5 text-[13px] text-gray-700">{row.phoneNumber || '—'}</td>
                      <td className="px-5 py-3.5"><ExpiryCell days={row.visaDaysLeft} date={row.visaExpiryDate} /></td>
                      <td className="px-5 py-3.5"><ExpiryCell days={row.passportDaysLeft} date={row.passportExpiryDate} /></td>
                      <td className="px-5 py-3.5"><ExpiryCell days={row.emiratesIdDaysLeft} date={row.emiratesIdExpiryDate} /></td>
                    </tr>
                  ))}
                  {expiryReport.data.rows?.length > 0 && expirySort.sorted.length === 0 && (
                    <tr><td colSpan={6} className="py-12 text-center text-[13px] text-gray-400">No employees match your search</td></tr>
                  )}
                </tbody>
              </table>
            )}
            {!expiryReport.isLoading && expiryReport.data?.rows?.length === 0 && (
              <div className="py-12 text-center text-[13px] text-green-600">
                ✓ No documents expiring within {expiryDays} days
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

function ExpiryCell({ days, date }: { days: number | null; date: string | null }) {
  if (!date || days === null) return <span className="text-[12px] text-gray-300">—</span>;
  const cls = days < 0 ? 'text-red-700 font-semibold' : days <= 30 ? 'text-amber-700 font-medium' : 'text-gray-700';
  return (
    <div>
      <div className={`text-[12px] ${cls}`}>{date}</div>
      <div className={`text-[11px] ${days < 0 ? 'text-red-500' : 'text-gray-400'}`}>
        {days < 0 ? `Expired ${Math.abs(days)}d ago` : `${days}d left`}
      </div>
    </div>
  );
}

function Spinner() {
  return (
    <svg className="h-4 w-4 animate-spin text-blue-600" viewBox="0 0 24 24" fill="none">
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"/>
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z"/>
    </svg>
  );
}

function TableSkeleton({ cols, rows }: { cols: number; rows: number }) {
  return (
    <div className="divide-y divide-gray-50">
      {Array.from({ length: rows }).map((_, i) => (
        <div key={i} className="flex gap-4 px-5 py-4">
          {Array.from({ length: cols }).map((_, j) => (
            <div key={j} className="h-3.5 flex-1 rounded bg-gray-100 animate-pulse"/>
          ))}
        </div>
      ))}
    </div>
  );
}
